Add model_loader.cpp to daemon CMakeLists
Fixes linker error: 'ModelLoader::load_model' and 'ModelLoader::ModelLoader'
undefined symbols.

The model_loader.cpp file was created but not added to DAEMON_SOURCES,
causing linker errors when RestServer tried to use ModelLoader.

Added server/model_loader.cpp to DAEMON_SOURCES list.

Fixes:
  Undefined symbols for architecture arm64:
    "mlxr::server::ModelLoader::load_model(...)"
    "mlxr::server::ModelLoader::ModelLoader(...)"
  ld: symbol(s) not found for architecture arm64